/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/expense-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Expense Groups
         * @description Получить все группы расходов.
         */
        get: operations["get_expense_groups_api_expense_groups_get"];
        put?: never;
        /**
         * Create Expense Group
         * @description Создать новую группу расходов.
         */
        post: operations["create_expense_group_api_expense_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense-groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Expense Group
         * @description Получить группу расходов по ID.
         */
        get: operations["get_expense_group_api_expense_groups__group_id__get"];
        /**
         * Update Expense Group
         * @description Обновить группу расходов.
         */
        put: operations["update_expense_group_api_expense_groups__group_id__put"];
        post?: never;
        /**
         * Delete Expense Group
         * @description Удалить группу расходов.
         */
        delete: operations["delete_expense_group_api_expense_groups__group_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Expense Items
         * @description Получить расходы с фильтрацией по месяцу/году.
         */
        get: operations["get_expense_items_api_expense_items_get"];
        put?: never;
        /**
         * Create Expense Item
         * @description Создать новый расход с валидацией через ExpenseItemCreate.
         */
        post: operations["create_expense_item_api_expense_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expense-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Expense Item
         * @description Получить расход по ID.
         */
        get: operations["get_expense_item_api_expense_items__item_id__get"];
        /**
         * Update Expense Item
         * @description Обновить расход с поддержкой partial update (PATCH semantics).
         */
        put: operations["update_expense_item_api_expense_items__item_id__put"];
        post?: never;
        /**
         * Delete Expense Item
         * @description Удалить расход.
         */
        delete: operations["delete_expense_item_api_expense_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vacations
         * @description Получить все отпускные.
         */
        get: operations["get_vacations_api_vacations_get"];
        put?: never;
        /**
         * Create Vacation
         * @description Создать новое начисление (отпускные) с валидацией через VacationCreate.
         *
         *     startDate/endDate — необязательный диапазон отпуска: если указан, дни
         *     отпуска, попадающие на рабочие дни, вычитаются из базы расчёта обычной
         *     зарплаты методом "по рабочим дням" (см. SalaryCalculator). Без диапазона
         *     отпуск учитывается только как надбавка к выплате на дату payoutDate —
         *     как раньше.
         */
        post: operations["create_vacation_api_vacations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacations/{vacation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Vacation
         * @description Удалить начисление.
         */
        delete: operations["delete_vacation_api_vacations__vacation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/birthdays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Birthdays
         * @description Получить все дни рождения.
         */
        get: operations["get_birthdays_api_birthdays_get"];
        put?: never;
        /**
         * Create Birthday
         * @description Добавить день рождения с валидацией через BirthdayCreate.
         */
        post: operations["create_birthday_api_birthdays_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/birthdays/{birthday_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Birthday
         * @description Обновить день рождения (partial update). db.update_birthday требует
         *     полный набор полей, поэтому недостающие берём из текущей записи —
         *     тот же паттерн, что и update_expense_item.
         */
        put: operations["update_birthday_api_birthdays__birthday_id__put"];
        post?: never;
        /**
         * Delete Birthday
         * @description Удалить день рождения.
         */
        delete: operations["delete_birthday_api_birthdays__birthday_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/birthdays/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upcoming Birthdays
         * @description Дни рождения, триггер напоминания которых попадает в ближайшие N дней.
         */
        get: operations["get_upcoming_birthdays_api_birthdays_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/birthdays/auto-create-expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto Create Birthday Expenses
         * @description Создать расходы на подарки для ДР, чей триггер (-14 дней) попал в текущий месяц.
         */
        post: operations["auto_create_birthday_expenses_api_birthdays_auto_create_expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Получить настройки зарплаты.
         */
        get: operations["get_settings_api_settings_get"];
        /**
         * Update Settings
         * @description Обновить настройки зарплаты.
         */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Balance
         * @description Полный расчёт баланса за период: ЗП (с учётом выбранного метода
         *     распределения по половинам месяца) + отпускные - расходы.
         */
        get: operations["get_balance_api_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Debts
         * @description Получить все долги.
         */
        get: operations["get_debts_api_debts_get"];
        put?: never;
        /**
         * Create Debt
         * @description Создать новый долг.
         */
        post: operations["create_debt_api_debts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debts/{debt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Debt
         * @description Удалить долг.
         */
        delete: operations["delete_debt_api_debts__debt_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debts/{debt_id}/repayments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Debt Repayment
         * @description Добавить погашение долга.
         */
        post: operations["add_debt_repayment_api_debts__debt_id__repayments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debts/repayments/{repayment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Debt Repayment
         * @description Удалить погашение долга.
         */
        delete: operations["delete_debt_repayment_api_debts_repayments__repayment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytics Summary
         * @description Получить сводную аналитику расходов.
         */
        get: operations["get_analytics_summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Проверка здоровья API.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Spa
         * @description SPA-fallback: любой путь, не совпавший ни с одним /api/... эндпоинтом
         *     выше и не с /assets, отдаёт index.html — дальше маршрутизацией занимается
         *     React Router на клиенте (поэтому прямой переход на /settings, /expenses
         *     и т.д. по URL или обновление страницы работает без 404).
         *
         *     Регистрация в самом конце файла обязательна: FastAPI матчит маршруты по
         *     порядку регистрации, и этот catch-all не должен перехватывать /api/*.
         */
        get: operations["serve_spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsCategory */
        AnalyticsCategory: {
            /** Name */
            name: string;
            /** Amount */
            amount: number;
            /** Color */
            color: string;
        };
        /** AnalyticsSummaryResponse */
        AnalyticsSummaryResponse: {
            /** Total */
            total: number;
            /** Count */
            count: number;
            /** Categories */
            categories: components["schemas"]["AnalyticsCategory"][];
        };
        /**
         * BalanceResponse
         * @description Полный расчёт баланса: зарплата + отпускные - расходы, по половинам месяца.
         */
        BalanceResponse: {
            /** Month */
            month: number;
            /** Year */
            year: number;
            /** Netsalary */
            netSalary: number;
            /** Advance */
            advance: number;
            /** Payout */
            payout: number;
            /** Vacationhalf1 */
            vacationHalf1: number;
            /** Vacationhalf2 */
            vacationHalf2: number;
            /** Totalaccrued */
            totalAccrued: number;
            /** Topayhalf1 */
            toPayHalf1: number;
            /** Topayhalf2 */
            toPayHalf2: number;
            /** Expenseshalf1 */
            expensesHalf1: number;
            /** Expenseshalf2 */
            expensesHalf2: number;
            /** Balancehalf1 */
            balanceHalf1: number;
            /** Balancehalf2 */
            balanceHalf2: number;
            /** Calculationmethod */
            calculationMethod: string;
            /** Workingdayshalf1 */
            workingDaysHalf1?: number | null;
            /** Workingdayshalf2 */
            workingDaysHalf2?: number | null;
            /** Workingdaystotal */
            workingDaysTotal?: number | null;
            /** Advancecutoffday */
            advanceCutoffDay?: number | null;
            /** Payoutdate1 */
            payoutDate1?: string | null;
            /** Payoutdate2 */
            payoutDate2?: string | null;
            /** Payoutdate1Nominal */
            payoutDate1Nominal?: string | null;
            /** Payoutdate2Nominal */
            payoutDate2Nominal?: string | null;
        };
        /** BirthdayAlertResponse */
        BirthdayAlertResponse: {
            /** Name */
            name: string;
            /** Birthdate */
            birthDate: string;
            /** Giftamount */
            giftAmount: number;
            /** Triggerdate */
            triggerDate: string;
            /** Daysuntil */
            daysUntil: number;
        };
        /** BirthdayCreate */
        BirthdayCreate: {
            /** Name */
            name: string;
            /**
             * Birthdate
             * @description Дата рождения в формате DD.MM.YYYY
             */
            birthDate: string;
            /** Giftamount */
            giftAmount: number;
        };
        /** BirthdayResponse */
        BirthdayResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Birthdate */
            birthDate: string;
            /** Giftamount */
            giftAmount: number;
        };
        /** BirthdayUpdate */
        BirthdayUpdate: {
            /** Name */
            name?: string | null;
            /**
             * Birthdate
             * @description Дата рождения в формате DD.MM.YYYY
             */
            birthDate?: string | null;
            /** Giftamount */
            giftAmount?: number | null;
        };
        /** DebtCreate */
        DebtCreate: {
            /** Title */
            title: string;
            /** Totalamount */
            totalAmount: number;
            /** Month */
            month: number;
            /** Year */
            year: number;
        };
        /** DebtResponse */
        DebtResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Totalamount */
            totalAmount: number;
            /**
             * Repayments
             * @default []
             */
            repayments: components["schemas"]["RepaymentResponse"][];
            /** Createdat */
            createdAt: string;
            /** Month */
            month: number;
            /** Year */
            year: number;
        };
        /** ExpenseGroupCreate */
        ExpenseGroupCreate: {
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Parentid */
            parentId?: string | null;
        };
        /** ExpenseGroupResponse */
        ExpenseGroupResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Parentid */
            parentId?: string | null;
            /**
             * Sortorder
             * @default 0
             */
            sortOrder: number;
        };
        /** ExpenseGroupUpdate */
        ExpenseGroupUpdate: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
            /** Parentid */
            parentId?: string | null;
            /** Sortorder */
            sortOrder?: number | null;
        };
        /** ExpenseItemCreate */
        ExpenseItemCreate: {
            /** Name */
            name: string;
            /** Amount */
            amount: number;
            /** Half */
            half: number;
            /** Month */
            month: number;
            /** Year */
            year: number;
            /**
             * Isrecurring
             * @default false
             */
            isRecurring: boolean;
            /** Groupid */
            groupId?: string | null;
            /** Recurringuntil */
            recurringUntil?: string | null;
        };
        /** ExpenseItemResponse */
        ExpenseItemResponse: {
            /** Id */
            id: string;
            /** Groupid */
            groupId?: string | null;
            /** Name */
            name: string;
            /** Amount */
            amount: number;
            /** Date */
            date?: string | null;
            /**
             * Isinclusive
             * @default false
             */
            isInclusive: boolean;
            /** Half */
            half: number;
            /** Isrecurring */
            isRecurring: boolean;
            /** Recurringuntil */
            recurringUntil?: string | null;
            /** Month */
            month: number;
            /** Year */
            year: number;
        };
        /** ExpenseItemUpdate */
        ExpenseItemUpdate: {
            /** Name */
            name?: string | null;
            /** Amount */
            amount?: number | null;
            /** Half */
            half?: number | null;
            /** Isrecurring */
            isRecurring?: boolean | null;
            /** Groupid */
            groupId?: string | null;
            /** Recurringuntil */
            recurringUntil?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RepaymentCreate */
        RepaymentCreate: {
            /** Amount */
            amount: number;
            /** Date */
            date: string;
            /** Note */
            note?: string | null;
        };
        /** RepaymentResponse */
        RepaymentResponse: {
            /** Id */
            id: string;
            /** Debtid */
            debtId: string;
            /** Amount */
            amount: number;
            /** Date */
            date: string;
            /** Note */
            note?: string | null;
        };
        /** SalarySettingsResponse */
        SalarySettingsResponse: {
            /** Basesalary */
            baseSalary: number;
            /** Taxrate */
            taxRate: number;
            /** Kef */
            kef: number;
            /** Advancecutoffday */
            advanceCutoffDay: number;
            /** Isadvancedateinclusive */
            isAdvanceDateInclusive: boolean;
            /** Accountshortened */
            accountShortened: boolean;
            /** Standardhours */
            standardHours: number;
            /**
             * Payoutday1
             * @default 10
             */
            payoutDay1: number;
            /**
             * Payoutday2
             * @default 25
             */
            payoutDay2: number;
            /**
             * Moveweekendtofriday
             * @default true
             */
            moveWeekendToFriday: boolean;
            /**
             * Salarycalculationmethod
             * @default proportional
             */
            salaryCalculationMethod: string;
            /**
             * Firsthalfratio
             * @default 0.4
             */
            firstHalfRatio: number;
            /**
             * Secondhalfratio
             * @default 0.6
             */
            secondHalfRatio: number;
        };
        /** SalarySettingsUpdate */
        SalarySettingsUpdate: {
            /** Basesalary */
            baseSalary?: number | null;
            /** Taxrate */
            taxRate?: number | null;
            /** Kef */
            kef?: number | null;
            /** Advancecutoffday */
            advanceCutoffDay?: number | null;
            /** Isadvancedateinclusive */
            isAdvanceDateInclusive?: boolean | null;
            /** Accountshortened */
            accountShortened?: boolean | null;
            /** Standardhours */
            standardHours?: number | null;
            /** Payoutday1 */
            payoutDay1?: number | null;
            /** Payoutday2 */
            payoutDay2?: number | null;
            /** Moveweekendtofriday */
            moveWeekendToFriday?: boolean | null;
            /** Salarycalculationmethod */
            salaryCalculationMethod?: string | null;
            /** Firsthalfratio */
            firstHalfRatio?: number | null;
            /** Secondhalfratio */
            secondHalfRatio?: number | null;
        };
        /** VacationCreate */
        VacationCreate: {
            /**
             * Totalamount
             * @description Сумма отпускных
             */
            totalAmount: number;
            /**
             * Payoutdate
             * @description Дата выплаты в формате YYYY-MM-DD
             */
            payoutDate: string;
            /**
             * Startdate
             * @description Первый день отпуска (YYYY-MM-DD); по умолчанию = payoutDate
             */
            startDate?: string | null;
            /**
             * Enddate
             * @description Последний день отпуска (YYYY-MM-DD); по умолчанию = payoutDate
             */
            endDate?: string | null;
        };
        /** VacationResponse */
        VacationResponse: {
            /** Id */
            id: string;
            /** Totalamount */
            totalAmount: number;
            /** Payoutdate */
            payoutDate: string;
            /** Startdate */
            startDate?: string | null;
            /** Enddate */
            endDate?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_expense_groups_api_expense_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseGroupResponse"][];
                };
            };
        };
    };
    create_expense_group_api_expense_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_expense_group_api_expense_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_expense_group_api_expense_groups__group_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseGroupUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_expense_group_api_expense_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_expense_items_api_expense_items_get: {
        parameters: {
            query?: {
                /** @description Месяц (1-12) */
                month?: number | null;
                /** @description Год (2020-2100) */
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expense_item_api_expense_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_expense_item_api_expense_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_expense_item_api_expense_items__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_expense_item_api_expense_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vacations_api_vacations_get: {
        parameters: {
            query?: {
                month?: number | null;
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vacation_api_vacations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_vacation_api_vacations__vacation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_birthdays_api_birthdays_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BirthdayResponse"][];
                };
            };
        };
    };
    create_birthday_api_birthdays_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BirthdayCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BirthdayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_birthday_api_birthdays__birthday_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                birthday_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BirthdayUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BirthdayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_birthday_api_birthdays__birthday_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                birthday_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upcoming_birthdays_api_birthdays_upcoming_get: {
        parameters: {
            query?: {
                /** @description Горизонт напоминания в днях */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BirthdayAlertResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auto_create_birthday_expenses_api_birthdays_auto_create_expenses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalarySettingsResponse"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalarySettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalarySettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_balance_api_balance_get: {
        parameters: {
            query: {
                month: number;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_debts_api_debts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtResponse"][];
                };
            };
        };
    };
    create_debt_api_debts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebtCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_debt_api_debts__debt_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_debt_repayment_api_debts__debt_id__repayments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepaymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_debt_repayment_api_debts_repayments__repayment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repayment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_summary_api_analytics_summary_get: {
        parameters: {
            query?: {
                month?: number | null;
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    serve_spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
